[package]
name = "jasmine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = {path = "../util"}
async-trait = "0.1.53"
tokio = {version = "1.18.2", features = ["full"]} 

[dependencies.redis]
version = "*"


